import { Nunito_Sans } from "next/font/google";
import "./globals.css";

export const nunito_sans = Nunito_Sans({
  subsets: ["latin"],
  weight: ["300", "600", "800"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={nunito_sans.className}>
      <body>{children}</body>
    </html>
  );
}
